CREATE DATABASE MY_DB -- CREATE A NEW DATABASE
-- 数据库操作
CREATE DATABASE TESTDB -- CREATE A NEW DATABASE CALLED TESTDB
DROP DATABASE TESTDB -- DROP DATABASE NAMED TESTDB

-- 数据库表操作
CREATE TABLE STUDENTS  -- CREATE A NEW TABLE
(
	ID INT,
	FIRSTNAME VARCHAR(255),
	LASTNAME VARCHAR(255)
)

CREATE TABLE MY_TABLE(ID INT) -- 新建数据库表
select * from MY_TABLE -- 查找数据库表中的数据
TRUNCATE TABLE MY_TABLE -- 清空数据库表中数据
DROP TABLE MY_TABLE -- 删除数据库表

ALTER TABLE MY_TABLE ADD EMAIL VARCHAR(255) -- 为my_table重新增email列
ALTER TABLE MY_TABLE DROP COLUMN EMAIL -- 删除my_table中的email列
ALTER TABLE MY_TABLE ALTER COLUMN ID VARCHAR(255) -- 更改my_table中列为ID的属性，值类型改为varchar（255）

